from typing import Protocol, Optional, List
from src.models.collection_model import CollectionModel
class ICollectionRepo(Protocol):
    def create(collection: CollectionModel) -> CollectionModel:...
    def find(id: str) -> Optional[CollectionModel]:...
    def find_by_uui(uui: str) -> Optional[List[CollectionModel]]:...
    def get_all() -> Optional[List[CollectionModel]]:...
