from typing import Protocol, Optional, List
from src.models.collection_model import CollectionModel
from src.models.user_model import UserModel
from src.schemas.collection import UpdateCollection

class ICollectionRepo(Protocol):
    def create(collection: CollectionModel) -> CollectionModel:...
    def find(id: str) -> Optional[CollectionModel]:...
    def find_by_uui(uui: str,limit: int, offset: int) -> Optional[List[CollectionModel]]:...
    def get_all(limit: int, offset: int) -> Optional[List[CollectionModel]]:...
    def update(data: UpdateCollection) -> Optional[CollectionModel]:...
    def get_timestaps_decs() -> Optional[CollectionModel]:...
    def get_latest_timestamp():...
    def get_user_by_id(id: str)-> Optional[UserModel]:...
