from typing import Protocol, Optional, List
from src.models.pixel_model import PhotoModel

class IPhotoRepo(Protocol):
    def create(photo: PhotoModel)-> PhotoModel:...
    def find(id: str) -> Optional[PhotoModel]:...
    def get_all() -> Optional[List[PhotoModel]]:...

