from typing import Protocol, Optional, List
from src.models.pixel_model import PixelModel

class IPixelRepo(Protocol):
    def create(pixel: PixelModel)-> PixelModel:...
    def find(id: str) -> Optional[PixelModel]:...
    def find_by_collection(id: str) -> Optional[List[PixelModel]]:...
    def get_all() -> Optional[List[PixelModel]]:...