from typing import Protocol, Optional, List
from src.models.pixel_model import PixelModel
from src.schemas.pixel import UpdatePixel

class IPixelRepo(Protocol):
    def create(pixel: PixelModel)-> PixelModel:...
    def find(id: str) -> Optional[PixelModel]:...
    def find_by_collection(id: str, limit: int, offset: int) -> Optional[List[PixelModel]]:...
    def get_all(limit: int, offset: int) -> Optional[List[PixelModel]]:...
    def update_pixel(id: str, data: UpdatePixel)-> Optional[PixelModel]:...
    def get_timestaps_decs() -> Optional[PixelModel]:...
    def get_latest_timestamp():...