from typing import Protocol, Optional, List
from src.models.social_model import SocialModel

class ISocialRepo(Protocol):
    def create(social: SocialModel)-> SocialModel:...
    def find(id: str)-> Optional[SocialModel]:...
    def find_by_uui(uui:str) -> Optional[List[SocialModel]]:...
    
