from typing import Protocol, Optional, List
from src.models.user_model import UserModel
from src.schemas.user import UpdateUser

class IUserRepo(Protocol):
    def create(user: UserModel)-> UserModel:...
    def find(uui:str)-> Optional[UserModel]:...
    def find_email(email:str)-> Optional[UserModel]:...
    def get_all()-> Optional[List[UserModel]]:...
    def login(email: str, password: str) -> Optional[UserModel]:...
    def update(data: UpdateUser) -> Optional[UserModel]:...