from typing import Protocol, Optional, List
from src.models.user_model import UserModel

class IUserRepo(Protocol):
    def create(user: UserModel)-> UserModel:...
    def find(uui:str)-> Optional[UserModel]:...
    def get_all()-> Optional[List[UserModel]]:...